baseurl: /church-website-template
timezone: /America/Denver
exclude: [README.md]
host: 127.0.0.1
collections:
  doc:
    call_to_worship: "???"
    songs:
      title: "???"
      page: nil
    offering_response: "???"
    scripture_reader: "???"
    closing_song:
      title: "???"
      page: nil
    sermon:
      title: "???"
      scriptures:
        "???"